name: example
description: example
steps:
  - description: "Step 1"
    exec:
      - command: mkdir
        args:
          - example
  - description: "Step 2"
    render:
      - template: templates/example_txt.tpl
        output: example/example.txt
        values:
          - tag: template_string
            description: "Wrote something ore push enter for default value"
            default: "Have a nice day"
  - description: "Step 3"
    exec:
      - script: scripts/example.sh
        ask:
          - description: "your name is?"
            default: "John Doe"
            tag: "name"
        args:
          - "{{.name}}"
